services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./api:/app
      - /app/node_modules
  # listener:
  #   build: ./listener
  #   depends_on:
  #     - api
  #   networks:
  #     - app-network
  #   restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
