name: CI

on:
  push:
    branches: [ Pipeline ]
  pull_request:
    branches: [ Pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Lint Docker Image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml run --rm api yarn lint

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.yml run --rm api yarn test
